# Generated by Django 2.1.3 on 2021-01-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='words',
        ),
    ]
